import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Auth
    'auth.adminLogin': 'Admin Login',
    'auth.staffLogin': 'Staff Login',
    'auth.name': 'Name',
    'auth.email': 'Email',
    'auth.phone': 'Phone Number',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.switchToStaff': 'Switch to Staff Login',
    'auth.switchToAdmin': 'Switch to Admin Login',
    'auth.welcome': 'Welcome Back',
    'auth.subtitle': 'Enter your credentials to access your account',

    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.staffManagement': 'Staff Management',
    'nav.userManagement': 'User Management',
    'nav.familyManagement': 'Family Management',
    'nav.permissions': 'Permissions',
    'nav.activityLogs': 'Activity Logs',
    'nav.analytics': 'Analytics',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',

    // Dashboard
    'dashboard.title': 'Dashboard Overview',
    'dashboard.welcome': 'Welcome to your admin dashboard',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.todayNewUsers': 'Today New Users',
    'dashboard.staffCount': 'Staff Count',
    'dashboard.newUsers': 'New Users',
    'dashboard.activeUsers': 'Active Users',
    'dashboard.inactiveUsers': 'Inactive Users',
    'dashboard.systemHealth': 'System Health',
    'dashboard.thisMonth': 'This month',
    'dashboard.vs30Days': 'vs last 30 days',
    'dashboard.uptime': 'Uptime',
    'dashboard.excellent': 'Excellent',
    'dashboard.realTimeData': 'Real-time Data',
    'dashboard.userStatistics': 'User Statistics',
    'dashboard.overviewMetrics': 'Overview of user metrics',
    'dashboard.recentUsers': 'Recent Users',
    'dashboard.newUserJoined': 'new user(s) joined recently',
    'dashboard.latest': 'Latest',
    'dashboard.name': 'Name',
    'dashboard.email': 'Email',
    'dashboard.joinDate': 'Join Date',
    'dashboard.status': 'Status',
    'dashboard.active': 'Active',
    'dashboard.noRecentUsers': 'No recent users found',
    'dashboard.loadingData': 'Loading dashboard data...',
    'dashboard.noDashboardData': 'No dashboard data',
    'dashboard.unableToLoad': 'Unable to load dashboard information',
    'dashboard.growing': 'Growing',
    'dashboard.declining': 'Declining',
    'dashboard.stable': 'Stable',
    'dashboard.users': 'users',
    'dashboard.staff': 'Staff',
    'dashboard.today': 'Today',
    'dashboard.todayNew': 'Today New',

    // Staff Management
    'staff.title': 'Staff Management',
    'staff.addStaff': 'Add Staff',
    'staff.createStaff': 'Create Staff',
    'staff.createNewStaff': 'Create New Staff',
    'staff.search': 'Search staff...',
    'staff.searchByMobileOrEmail': 'Search by mobile or email',
    'staff.name': 'Name',
    'staff.fullName': 'Full Name',
    'staff.email': 'Email',
    'staff.phone': 'Phone',
    'staff.mobileNumber': 'Mobile Number',
    'staff.password': 'Password',
    'staff.role': 'Role',
    'staff.status': 'Status',
    'staff.allStatus': 'All Status',
    'staff.actions': 'Actions',
    'staff.active': 'Active',
    'staff.inactive': 'Inactive',
    'staff.activate': 'Activate',
    'staff.activateStaff': 'Activate Staff',
    'staff.deactivate': 'Deactivate',
    'staff.deactivateStaff': 'Deactivate Staff',
    'staff.edit': 'Edit',
    'staff.delete': 'Delete',
    'staff.addNewStaff': 'Add New Staff',
    'staff.editStaff': 'Edit Staff',
    'staff.cancel': 'Cancel',
    'staff.save': 'Save',
    'staff.refresh': 'Refresh',
    'staff.id': 'ID',
    'staff.createdAt': 'Created At',
    'staff.lastLogin': 'Last Login',
    'staff.never': 'Never',
    'staff.noStaffFound': 'No staff members found',
    'staff.confirmAction': 'Confirm Action',
    'staff.areYouSure': 'Are you sure you want to',
    'staff.staffMember': 'staff member',
    'staff.staffDetails': 'Staff Details',
    'staff.currentStatus': 'Current Status',
    'staff.errorFetching': 'Error fetching staff list',
    'staff.errorToggling': 'Error toggling staff status',
    'staff.createdSuccessfully': 'Staff created successfully',
    'staff.failedToCreate': 'Failed to create staff',
    'staff.activatedSuccessfully': 'activated successfully',
    'staff.deactivatedSuccessfully': 'deactivated successfully',
    'EventManagement': 'Event Management',
    'ChatManagement': 'Chat Management',
    'PostManagement': 'Post Management',

    // User Management
    'users.title': 'User Management',
    'users.search': 'Search users...',
    'users.filter': 'Filter',
    'users.export': 'Export',
    'users.bulkActions': 'Bulk Actions',
    'users.selectAll': 'Select All',
    'users.id': 'ID',
    'users.name': 'Name',
    'users.email': 'Email',
    'users.phone': 'Phone',
    'users.joinedDate': 'Joined Date',
    'users.status': 'Status',
    'users.actions': 'Actions',
    'users.view': 'View',
    'users.edit': 'Edit',
    'users.delete': 'Delete',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    'users.suspended': 'Suspended',
    'users.allStatus': 'All Status',
    'users.selected': 'selected',

    // Permissions
    'permissions.title': 'Permissions Management',
    'permissions.templates': 'Permission Templates',
    'permissions.createTemplate': 'Create Template',
    'permissions.templateName': 'Template Name',
    'permissions.description': 'Description',
    'permissions.assignedTo': 'Assigned To',
    'permissions.actions': 'Actions',
    'permissions.edit': 'Edit',
    'permissions.delete': 'Delete',
    'permissions.assign': 'Assign',
    'permissions.viewPermissions': 'View Permissions',
    'permissions.dashboard': 'Dashboard',
    'permissions.staffMgmt': 'Staff Management',
    'permissions.userMgmt': 'User Management',
    'permissions.permissionsMgmt': 'Permissions Management',
    'permissions.logs': 'Activity Logs',
    'permissions.analytics': 'Analytics',
    'permissions.settings': 'Settings',
    'permissions.read': 'Read',
    'permissions.write': 'Write',

    // Activity Logs
    'logs.title': 'Activity Logs',
    'logs.search': 'Search logs...',
    'logs.filter': 'Filter',
    'logs.export': 'Export',
    'logs.timestamp': 'Timestamp',
    'logs.user': 'User',
    'logs.action': 'Action',
    'logs.details': 'Details',
    'logs.ipAddress': 'IP Address',
    'logs.allActions': 'All Actions',
    'logs.login': 'Login',
    'logs.logout': 'Logout',
    'logs.create': 'Create',
    'logs.update': 'Update',
    'logs.delete': 'Delete',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.userGrowth': 'User Growth',
    'analytics.userDistribution': 'User Distribution by Role',
    'analytics.activeUsers': 'Active Users Trend',
    'analytics.users': 'Users',
    'analytics.month': 'Month',
    'analytics.admin': 'Admin',
    'analytics.staff': 'Staff',
    'analytics.regularUsers': 'Regular Users',

    // Profile
    'profile.title': 'Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.role': 'Role',
    'profile.save': 'Save Changes',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm New Password',
    'profile.updatePassword': 'Update Password',

    // Settings
    'settings.title': 'System Settings',
    'settings.general': 'General Settings',
    'settings.systemName': 'System Name',
    'settings.timezone': 'Timezone',
    'settings.language': 'Language',
    'settings.dateFormat': 'Date Format',
    'settings.save': 'Save Settings',
    'settings.security': 'Security Settings',
    'settings.twoFactor': 'Two-Factor Authentication',
    'settings.sessionTimeout': 'Session Timeout',
    'settings.passwordPolicy': 'Password Policy',
    'settings.enabled': 'Enabled',
    'settings.disabled': 'Disabled',
    'settings.minutes': 'minutes',
    'settings.systemStatus': 'System Status',
    'settings.database': 'Database',
    'settings.storage': 'Storage',
    'settings.api': 'API',
    'settings.operational': 'Operational',

    // Common
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.search': 'Search',
    'common.close': 'Close',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
  },
  ta: {
    // Auth
    'auth.adminLogin': 'நிர்வாகி உள்நுழைவு',
    'auth.staffLogin': 'ஊழியர் உள்நுழைவு',
    'auth.name': 'பெயர்',
    'auth.email': 'மின்னஞ்சல்',
    'auth.phone': 'தொலைபேசி எண்',
    'auth.password': 'கடவுச்சொல்',
    'auth.confirmPassword': 'கடவுச்சொல்லை உறுதிப்படுத்து',
    'auth.login': 'உள்நுழைய',
    'auth.register': 'பதிவு செய்க',
    'auth.forgotPassword': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'auth.switchToStaff': 'ஊழியர் உள்நுழைவுக்கு மாறு',
    'auth.switchToAdmin': 'நிர்வாகி உள்நுழைவுக்கு மாறு',
    'auth.welcome': 'மீண்டும் வரவேற்கிறோம்',
    'auth.subtitle': 'உங்கள் கணக்கை அணுக உங்கள் விவரங்களை உள்ளிடவும்',
    'auth.mobileNumberMustBe10Digits': 'மொபைல் எண் சரியாக 10 இலக்கங்களாக இருக்க வேண்டும்',
    'auth.enterValidMobile': 'செல்லுபடியாகும் 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்',
    'auth.invalidCredentials': 'தவறான கணக்கு விவரங்கள். உங்கள் விவரங்களைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்',
    'auth.logo': 'லோகோ',
    'auth.signingIn': 'உள்நுழைகிறது...',
    'auth.enterCredentials': 'உள்நுழைய உங்கள் கணக்கு விவரங்களை உள்ளிடவும்',


    // Sidebar
    'nav.dashboard': 'கட்டுப்பாட்டு பலகை',
    'nav.staffManagement': 'ஊழியர் மேலாண்மை',
    'nav.userManagement': 'பயனர் மேலாண்மை',
    'nav.permissions': 'அனுமதிகள்',
    'nav.familyManagement': 'குடும்ப மேலாண்மை',
    'nav.activityLogs': 'செயல்பாட்டு பதிவுகள்',
    'nav.analytics': 'பகுப்பாய்வு',
    'nav.profile': 'சுயவிவரம்',
    'nav.settings': 'அமைப்புகள்',
    'nav.logout': 'வெளியேறு',

    // Event Management
    'eventManagement.title': 'நிகழ்வு',
    'eventManagement.management': 'மேலாண்மை',
    'eventManagement.description': 'சமூகம் நிகழ்வு வாழ்க்கை முழுமை மேலாண்மை. உளவியலை மடக்களப்பு, ஈடுபடு அளவீடுகளை பகுப்பாய்வும், மேடைபார்ம் தரந்திரங்களை பராமரிக்கவும்.',
    'eventManagement.moderation': 'மடக்களப்பு',
    'eventManagement.flagged': 'குறியிடப்பட்டது',
    'eventManagement.statistics': 'புள்ளிவிவரவுகள்',
    'eventManagement.sidebar': 'நிகழ்வு மேலாண்மை',

    // Chat Management
    'chatManagement.title': 'அரட்டை மேலாண்மை',
    'chatManagement.permissionDenied': 'அரட்டை மேலாண்மையை அணுக அனுமதிகள் இல்லை. உங்கள் நிர்வாகியைத் தொடர்பும்.',
    'chatManagement': 'அரட்டை மேலாண்மை',

    // Post Management
    'postManagement.title': 'இடுகை மேலாண்மை',
    'postManagement.permissionDenied': 'இடுகை மேலாண்மையை அணுக அனுமதிகள் இல்லை. உங்கள் நிர்வாகியைத் தொடர்பும்.',
    'postManagement': 'இடுகை மேலாண்மை',

    // Dashboard
    'dashboard.title': 'கட்டுப்பாட்டு பலகை மேலோட்டம்',
    'dashboard.welcome': 'உங்கள் நிர்வாக பலகைக்கு வரவேற்கிறோம்',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.todayNewUsers': 'இன்றைய புதிய பயனர்கள்',
    'dashboard.staffCount': 'ஊழியர் எண்ணிக்கை',
    'dashboard.newUsers': 'புதிய பயனர்கள்',
    'dashboard.activeUsers': 'செயலில் உள்ள பயனர்கள்',
    'dashboard.inactiveUsers': 'செயலற்ற பயனர்கள்',
    'dashboard.systemHealth': 'அமைப்பு நிலை',
    'dashboard.thisMonth': 'இந்த மாதம்',
    'dashboard.vs30Days': 'கடந்த 30 நாட்களுடன் ஒப்பிடும்போது',
    'dashboard.uptime': 'செயல்பாட்டு நேரம்',
    'dashboard.excellent': 'சிறப்பு',
    'dashboard.realTimeData': 'நேரடி தரவு',
    'dashboard.userStatistics': 'பயனர் புள்ளிவிவரங்கள்',
    'dashboard.overviewMetrics': 'பயனர் அளவீடுகளின் மேலோட்டம்',
    'dashboard.recentUsers': 'சமீபத்திய பயனர்கள்',
    'dashboard.newUserJoined': 'புதிய பயனர்(கள்) சமீபத்தில் சேர்ந்தனர்',
    'dashboard.latest': 'சமீபத்திய',
    'dashboard.name': 'பெயர்',
    'dashboard.email': 'மின்னஞ்சல்',
    'dashboard.joinDate': 'சேர்ந்த தேதி',
    'dashboard.status': 'நிலை',
    'dashboard.active': 'செயலில்',
    'dashboard.noRecentUsers': 'சமீபத்திய பயனர்கள் யாரும் கிடைக்கவில்லை',
    'dashboard.loadingData': 'பலகை தரவை ஏற்றுகிறது...',
    'dashboard.noDashboardData': 'பலகை தரவு இல்லை',
    'dashboard.unableToLoad': 'பலகை தகவலை ஏற்ற முடியவில்லை',
    'dashboard.growing': 'வளர்ந்து வருகிறது',
    'dashboard.declining': 'குறைந்து வருகிறது',
    'dashboard.stable': 'நிலையானது',
    'dashboard.users': 'பயனர்கள்',
    'dashboard.staff': 'ஊழியர்',
    'dashboard.today': 'இன்று',
    'dashboard.todayNew': 'இன்றைய புதியவை',

    // Staff Management
    'staff.title': 'ஊழியர் மேலாண்மை',
    'staff.addStaff': 'ஊழியரைச் சேர்க்கவும்',
    'staff.createStaff': 'ஊழியரை உருவாக்கு',
    'staff.createNewStaff': 'புதிய ஊழியரை உருவாக்கு',
    'staff.search': 'ஊழியரைத் தேடுங்கள்...',
    'staff.searchByMobileOrEmail': 'மொபைல் அல்லது மின்னஞ்சல் மூலம் தேடுங்கள்',
    'staff.name': 'பெயர்',
    'staff.fullName': 'முழு பெயர்',
    'staff.email': 'மின்னஞ்சல்',
    'staff.phone': 'தொலைபேசி',
    'staff.mobileNumber': 'மொபைல் எண்',
    'staff.password': 'கடவுச்சொல்',
    'staff.role': 'பங்கு',
    'staff.status': 'நிலை',
    'staff.allStatus': 'அனைத்து நிலைகள்',
    'staff.actions': 'செயல்கள்',
    'staff.active': 'செயலில்',
    'staff.inactive': 'செயலற்ற',
    'staff.activate': 'செயல்படுத்து',
    'staff.activateStaff': 'ஊழியரை செயல்படுத்து',
    'staff.deactivate': 'செயலிழக்கச் செய்',
    'staff.deactivateStaff': 'ஊழியரை செயலிழக்கச் செய்',
    'staff.edit': 'திருத்து',
    'staff.delete': 'நீக்கு',
    'staff.addNewStaff': 'புதிய ஊழியரைச் சேர்க்கவும்',
    'staff.editStaff': 'ஊழியரைத் திருத்து',
    'staff.cancel': 'ரத்துசெய்',
    'staff.save': 'சேமி',
    'staff.refresh': 'புதுப்பி',
    'staff.id': 'அடையாள எண்',
    'staff.createdAt': 'உருவாக்கப்பட்ட தேதி',
    'staff.lastLogin': 'கடைசி உள்நுழைவு',
    'staff.never': 'ஒருபோதும் இல்லை',
    'staff.noStaffFound': 'ஊழியர்கள் யாரும் கிடைக்கவில்லை',
    'staff.confirmAction': 'செயலை உறுதிப்படுத்து',
    'staff.areYouSure': 'நீங்கள் உறுதியாக விரும்புகிறீர்களா',
    'staff.staffMember': 'ஊழியர்',
    'staff.staffDetails': 'ஊழியர் விவரங்கள்',
    'staff.currentStatus': 'தற்போதைய நிலை',
    'staff.errorFetching': 'ஊழியர் பட்டியலைப் பெறுவதில் பிழை',
    'staff.errorToggling': 'ஊழியர் நிலையை மாற்றுவதில் பிழை',
    'staff.createdSuccessfully': 'ஊழியர் வெற்றிகரமாக உருவாக்கப்பட்டார்',
    'staff.failedToCreate': 'ஊழியரை உருவாக்க முடியவில்லை',
    'staff.activatedSuccessfully': 'வெற்றிகரமாக செயல்படுத்தப்பட்டது',
    'staff.deactivatedSuccessfully': 'வெற்றிகரமாக செயலிழக்கச் செய்யப்பட்டது',
    'nav.familyManagement': 'குடும்ப மேலாண்மை',
    'EventManagement': 'நிகழ்வு மேலாண்மை',
    'ChatManagement': 'அரட்டை மேலாண்மை',
    'PostManagement': 'இடுகை மேலாண்மை',

    // User Management
    'users.title': 'பயனர் மேலாண்மை',
    'users.search': 'பயனர்களைத் தேடுங்கள்...',
    'users.filter': 'வடிகட்டு',
    'users.export': 'ஏற்றுமதி',
    'users.bulkActions': 'மொத்த செயல்கள்',
    'users.selectAll': 'அனைத்தையும் தேர்ந்தெடு',
    'users.id': 'அடையாள எண்',
    'users.name': 'பெயர்',
    'users.email': 'மின்னஞ்சல்',
    'users.phone': 'தொலைபேசி',
    'users.joinedDate': 'சேர்ந்த தேதி',
    'users.status': 'நிலை',
    'users.actions': 'செயல்கள்',
    'users.view': 'பார்',
    'users.edit': 'திருத்து',
    'users.delete': 'நீக்கு',
    'users.active': 'செயலில்',
    'users.inactive': 'செயலற்ற',
    'users.suspended': 'இடைநிறுத்தப்பட்டது',
    'users.allStatus': 'அனைத்து நிலைகள்',
    'users.selected': 'தேர்ந்தெடுக்கப்பட்டது',

    // Permissions
    'permissions.title': 'அனுமதி மேலாண்மை',
    'permissions.templates': 'அனுமதி வார்ப்புருக்கள்',
    'permissions.createTemplate': 'வார்ப்புரு உருவாக்கு',
    'permissions.templateName': 'வார்ப்புரு பெயர்',
    'permissions.description': 'விளக்கம்',
    'permissions.assignedTo': 'ஒதுக்கப்பட்டது',
    'permissions.actions': 'செயல்கள்',
    'permissions.edit': 'திருத்து',
    'permissions.delete': 'நீக்கு',
    'permissions.assign': 'ஒதுக்கு',
    'permissions.viewPermissions': 'அனுமதிகளைக் காண்க',
    'permissions.dashboard': 'கட்டுப்பாட்டு பலகை',
    'permissions.staffMgmt': 'ஊழியர் மேலாண்மை',
    'permissions.userMgmt': 'பயனர் மேலாண்மை',
    'permissions.permissionsMgmt': 'அனுமதி மேலாண்மை',
    'permissions.logs': 'செயல்பாட்டு பதிவுகள்',
    'permissions.analytics': 'பகுப்பாய்வு',
    'permissions.settings': 'அமைப்புகள்',
    'permissions.read': 'படி',
    'permissions.write': 'எழுது',

    // Activity Logs
    'logs.title': 'செயல்பாட்டு பதிவுகள்',
    'logs.search': 'பதிவுகளைத் தேடுங்கள்...',
    'logs.filter': 'வடிகட்டு',
    'logs.export': 'ஏற்றுமதி',
    'logs.timestamp': 'நேர முத்திரை',
    'logs.user': 'பயனர்',
    'logs.action': 'செயல்',
    'logs.details': 'விவரங்கள்',
    'logs.ipAddress': 'ஐபி முகவரி',
    'logs.allActions': 'அனைத்து செயல்கள்',
    'logs.login': 'உள்நுழைவு',
    'logs.logout': 'வெளியேறு',
    'logs.create': 'உருவாக்கு',
    'logs.update': 'புதுப்பி',
    'logs.delete': 'நீக்கு',

    // Analytics
    'analytics.title': 'பகுப்பாய்வு',
    'analytics.userGrowth': 'பயனர் வளர்ச்சி',
    'analytics.userDistribution': 'பங்கின் அடிப்படையில் பயனர் விநியோகம்',
    'analytics.activeUsers': 'செயலில் உள்ள பயனர்கள் போக்கு',
    'analytics.users': 'பயனர்கள்',
    'analytics.month': 'மாதம்',
    'analytics.admin': 'நிர்வாகி',
    'analytics.staff': 'ஊழியர்',
    'analytics.regularUsers': 'வழக்கமான பயனர்கள்',

    // Profile
    'profile.title': 'சுயவிவரம்',
    'profile.personalInfo': 'தனிப்பட்ட தகவல்',
    'profile.name': 'பெயர்',
    'profile.email': 'மின்னஞ்சல்',
    'profile.phone': 'தொலைபேசி',
    'profile.role': 'பங்கு',
    'profile.save': 'மாற்றங்களைச் சேமி',
    'profile.changePassword': 'கடவுச்சொல்லை மாற்று',
    'profile.currentPassword': 'தற்போதைய கடவுச்சொல்',
    'profile.newPassword': 'புதிய கடவுச்சொல்',
    'profile.confirmPassword': 'புதிய கடவுச்சொல்லை உறுதிப்படுத்து',
    'profile.updatePassword': 'கடவுச்சொல்லை புதுப்பி',

    // Settings
    'settings.title': 'அமைப்பு அமைப்புகள்',
    'settings.general': 'பொது அமைப்புகள்',
    'settings.systemName': 'அமைப்பு பெயர்',
    'settings.timezone': 'நேர மண்டலம்',
    'settings.language': 'மொழி',
    'settings.dateFormat': 'தேதி வடிவம்',
    'settings.save': 'அமைப்புகளைச் சேமி',
    'settings.security': 'பாதுகாப்பு அமைப்புகள்',
    'settings.twoFactor': 'இரு-காரணி அங்கீகாரம்',
    'settings.sessionTimeout': 'அமர்வு காலாவதி',
    'settings.passwordPolicy': 'கடவுச்சொல் கொள்கை',
    'settings.enabled': 'இயக்கப்பட்டது',
    'settings.disabled': 'முடக்கப்பட்டது',
    'settings.minutes': 'நிமிடங்கள்',
    'settings.systemStatus': 'அமைப்பு நிலை',
    'settings.database': 'தரவுத்தளம்',
    'settings.storage': 'சேமிப்பு',
    'settings.api': 'ஏபிஐ',
    'settings.operational': 'செயல்பாட்டில்',

    // Common
    'common.loading': 'ஏற்றுகிறது...',
    'common.noData': 'தரவு கிடைக்கவில்லை',
    'common.search': 'தேடு',
    'common.close': 'மூடு',
    'common.submit': 'சமர்ப்பிக்கவும்',
    'common.reset': 'மீட்டமை',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
